## Librerias

In [1]:
import requests
import json
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Tabla de races

In [2]:
races = {'season':[],
        'round':[],
        'raceId':[],
        'circuitId':[],
        'lat':[],
        'long':[],
        'country':[],
        'date':[],
        'url':[]}

In [3]:
for year in list(range(2010,2023)):
    url = 'https://ergast.com/api/f1/{}.json'
    response = requests.get(url.format(year))
    content = json.loads(response.content)
    
    for item in content['MRData']['RaceTable']['Races']:
        races['season'].append(int(item['season']))
        races['round'].append(int(item['round']))
        races['raceId'].append(item['raceName'])
        races['circuitId'].append(item['Circuit']['circuitId'])
        races['lat'].append(item['Circuit']['Location']['lat'])
        races['long'].append(item['Circuit']['Location']['long'])
        races['country'].append(item['Circuit']['Location']['country'])
        races['date'].append(item['date'])
        races['url'].append(item['url'])

In [4]:
pd.DataFrame(races).to_csv('races.csv')

In [29]:
url = "https://ergast.com/api/f1/2022/22/results.json"
response = requests.get(url)

In [30]:
content = json.loads(response.content)

In [31]:
pd.DataFrame(content['MRData']['RaceTable']['Races'][0]['Results'])

,number,position,positionText,points,Driver,Constructor,grid,laps,status,Time,FastestLap
0,1,1,1,25,"{'driverId': 'max_verstappen', 'permanentNumbe...","{'constructorId': 'red_bull', 'url': 'http://e...",1,58,Finished,"{'millis': '5265914', 'time': '1:27:45.914'}","{'rank': '6', 'lap': '54', 'Time': {'time': '1..."
1,16,2,2,18,"{'driverId': 'leclerc', 'permanentNumber': '16...","{'constructorId': 'ferrari', 'url': 'http://en...",3,58,Finished,"{'millis': '5274685', 'time': '+8.771'}","{'rank': '10', 'lap': '48', 'Time': {'time': '..."
2,11,3,3,15,"{'driverId': 'perez', 'permanentNumber': '11',...","{'constructorId': 'red_bull', 'url': 'http://e...",2,58,Finished,"{'millis': '5276007', 'time': '+10.093'}","{'rank': '4', 'lap': '52', 'Time': {'time': '1..."
3,55,4,4,12,"{'driverId': 'sainz', 'permanentNumber': '55',...","{'constructorId': 'ferrari', 'url': 'http://en...",4,58,Finished,"{'millis': '5290806', 'time': '+24.892'}","{'rank': '3', 'lap': '50', 'Time': {'time': '1..."
4,63,5,5,10,"{'driverId': 'russell', 'permanentNumber': '63...","{'constructorId': 'mercedes', 'url': 'http://e...",6,58,Finished,"{'millis': '5301802', 'time': '+35.888'}","{'rank': '2', 'lap': '48', 'Time': {'time': '1..."
5,4,6,6,9,"{'driverId': 'norris', 'permanentNumber': '4',...","{'constructorId': 'mclaren', 'url': 'http://en...",7,58,Finished,"{'millis': '5322148', 'time': '+56.234'}","{'rank': '1', 'lap': '44', 'Time': {'time': '1..."
6,31,7,7,6,"{'driverId': 'ocon', 'permanentNumber': '31', ...","{'constructorId': 'alpine', 'url': 'http://en....",8,58,Finished,"{'millis': '5323154', 'time': '+57.240'}","{'rank': '5', 'lap': '45', 'Time': {'time': '1..."
7,18,8,8,4,"{'driverId': 'stroll', 'permanentNumber': '18'...","{'constructorId': 'aston_martin', 'url': 'http...",14,58,Finished,"{'millis': '5342845', 'time': '+1:16.931'}","{'rank': '9', 'lap': '42', 'Time': {'time': '1..."
8,3,9,9,2,"{'driverId': 'ricciardo', 'permanentNumber': '...","{'constructorId': 'mclaren', 'url': 'http://en...",13,58,Finished,"{'millis': '5349182', 'time': '+1:23.268'}","{'rank': '18', 'lap': '45', 'Time': {'time': '..."
9,5,10,10,1,"{'driverId': 'vettel', 'permanentNumber': '5',...","{'constructorId': 'aston_martin', 'url': 'http...",9,58,Finished,"{'millis': '5349812', 'time': '+1:23.898'}","{'rank': '15', 'lap': '35', 'Time': {'time': '..."
10,22,11,11,0,"{'driverId': 'tsunoda', 'permanentNumber': '22...","{'constructorId': 'alphatauri', 'url': 'http:/...",11,58,Finished,"{'millis': '5355285', 'time': '+1:29.371'}","{'rank': '7', 'lap': '40', 'Time': {'time': '1..."
11,24,12,12,0,"{'driverId': 'zhou', 'permanentNumber': '24', ...","{'constructorId': 'alfa', 'url': 'http://en.wi...",15,57,+1 Lap,NaN,"{'rank': '8', 'lap': '53', 'Time': {'time': '1..."
12,23,13,13,0,"{'driverId': 'albon', 'permanentNumber': '23',...","{'constructorId': 'williams', 'url': 'http://e...",19,57,+1 Lap,NaN,"{'rank': '13', 'lap': '40', 'Time': {'time': '..."
13,10,14,14,0,"{'driverId': 'gasly', 'permanentNumber': '10',...","{'constructorId': 'alphatauri', 'url': 'http:/...",17,57,+1 Lap,NaN,"{'rank': '19', 'lap': '16', 'Time': {'time': '..."
14,77,15,15,0,"{'driverId': 'bottas', 'permanentNumber': '77'...","{'constructorId': 'alfa', 'url': 'http://en.wi...",18,57,+1 Lap,NaN,"{'rank': '16', 'lap': '47', 'Time': {'time': '..."
15,47,16,16,0,"{'driverId': 'mick_schumacher', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",12,57,+1 Lap,NaN,"{'rank': '12', 'lap': '39', 'Time': {'time': '..."
16,20,17,17,0,"{'driverId': 'kevin_magnussen', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",16,57,+1 Lap,NaN,"{'rank': '20', 'lap': '40', 'Time': {'time': '..."
17,44,18,18,0,"{'driverId': 'hamilton', 'permanentNumber': '4...","{'constructorId': 'mercedes', 'url': 'http://e...",5,55,Hydraulics,NaN,"{'rank': '11', 'lap': '42', 'Time': {'time': '..."
18,6,19,19,0,"{'driverId': 'latifi', 'permanentNumber': '6',...","{'constructorId': 'williams', 'url': 'http://e...",20,55,Collision damage,NaN,"{'rank': '14', 'lap': '45', 'Time': {'time': '..."
19,14,20,R,0,"{'driverId': 'alonso', 'permanentNumber': '14'...","{'constructorId': 'alpine', 'url': 'http://en....",10,27,Water leak,NaN,"{'rank': '17', 'lap': '24', 'Time': {'time': '..."

## Tabla de resultados

In [5]:
list(range(1,23))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [89]:
df_results_2022=pd.DataFrame()
for race in list(range(1,23)):
    url = 'https://ergast.com/api/f1/2022/{}/results.json'
    response = requests.get(url.format(race))
    content = json.loads(response.content)
    df_results_2022 = df_results_2022.append(pd.DataFrame(content['MRData']['RaceTable']['Races'][0]['Results']))

In [7]:
type(df_results_2022.points.values[0])

str

In [8]:
type(df_results_2022.points.astype(int).values[0])

numpy.int32

In [33]:
df_results_2022['points']=df_results_2022.points.astype(int)

In [34]:
df_results_2022.groupby(['position']).agg({'points':'sum'}).sort_values(by='points', ascending=False)

          points
position
1            550
2            396
3            330
4            264
5            220
6            198
7            132
8             88
9             44
10            22
18             0
17             0
20             0
16             0
15             0
14             0
13             0
12             0
11             0
19             0

In [11]:
content['MRData']['RaceTable']['Races'][0]['Results'][0]

{'number': '1',
 'position': '1',
 'positionText': '1',
 'points': '25',
 'Driver': {'driverId': 'max_verstappen',
  'permanentNumber': '33',
  'code': 'VER',
  'url': 'http://en.wikipedia.org/wiki/Max_Verstappen',
  'givenName': 'Max',
  'familyName': 'Verstappen',
  'dateOfBirth': '1997-09-30',
  'nationality': 'Dutch'},
 'Constructor': {'constructorId': 'red_bull',
  'url': 'http://en.wikipedia.org/wiki/Red_Bull_Racing',
  'name': 'Red Bull',
  'nationality': 'Austrian'},
 'grid': '1',
 'laps': '58',
 'status': 'Finished',
 'Time': {'millis': '5265914', 'time': '1:27:45.914'},
 'FastestLap': {'rank': '6',
  'lap': '54',
  'Time': {'time': '1:29.392'},
  'AverageSpeed': {'units': 'kph', 'speed': '212.676'}}}

In [35]:
pd.DataFrame(content['MRData']['RaceTable']['Races'][0]['Results'])

,number,position,positionText,points,Driver,Constructor,grid,laps,status,Time,FastestLap
0,1,1,1,25,"{'driverId': 'max_verstappen', 'permanentNumbe...","{'constructorId': 'red_bull', 'url': 'http://e...",1,58,Finished,"{'millis': '5265914', 'time': '1:27:45.914'}","{'rank': '6', 'lap': '54', 'Time': {'time': '1..."
1,16,2,2,18,"{'driverId': 'leclerc', 'permanentNumber': '16...","{'constructorId': 'ferrari', 'url': 'http://en...",3,58,Finished,"{'millis': '5274685', 'time': '+8.771'}","{'rank': '10', 'lap': '48', 'Time': {'time': '..."
2,11,3,3,15,"{'driverId': 'perez', 'permanentNumber': '11',...","{'constructorId': 'red_bull', 'url': 'http://e...",2,58,Finished,"{'millis': '5276007', 'time': '+10.093'}","{'rank': '4', 'lap': '52', 'Time': {'time': '1..."
3,55,4,4,12,"{'driverId': 'sainz', 'permanentNumber': '55',...","{'constructorId': 'ferrari', 'url': 'http://en...",4,58,Finished,"{'millis': '5290806', 'time': '+24.892'}","{'rank': '3', 'lap': '50', 'Time': {'time': '1..."
4,63,5,5,10,"{'driverId': 'russell', 'permanentNumber': '63...","{'constructorId': 'mercedes', 'url': 'http://e...",6,58,Finished,"{'millis': '5301802', 'time': '+35.888'}","{'rank': '2', 'lap': '48', 'Time': {'time': '1..."
5,4,6,6,9,"{'driverId': 'norris', 'permanentNumber': '4',...","{'constructorId': 'mclaren', 'url': 'http://en...",7,58,Finished,"{'millis': '5322148', 'time': '+56.234'}","{'rank': '1', 'lap': '44', 'Time': {'time': '1..."
6,31,7,7,6,"{'driverId': 'ocon', 'permanentNumber': '31', ...","{'constructorId': 'alpine', 'url': 'http://en....",8,58,Finished,"{'millis': '5323154', 'time': '+57.240'}","{'rank': '5', 'lap': '45', 'Time': {'time': '1..."
7,18,8,8,4,"{'driverId': 'stroll', 'permanentNumber': '18'...","{'constructorId': 'aston_martin', 'url': 'http...",14,58,Finished,"{'millis': '5342845', 'time': '+1:16.931'}","{'rank': '9', 'lap': '42', 'Time': {'time': '1..."
8,3,9,9,2,"{'driverId': 'ricciardo', 'permanentNumber': '...","{'constructorId': 'mclaren', 'url': 'http://en...",13,58,Finished,"{'millis': '5349182', 'time': '+1:23.268'}","{'rank': '18', 'lap': '45', 'Time': {'time': '..."
9,5,10,10,1,"{'driverId': 'vettel', 'permanentNumber': '5',...","{'constructorId': 'aston_martin', 'url': 'http...",9,58,Finished,"{'millis': '5349812', 'time': '+1:23.898'}","{'rank': '15', 'lap': '35', 'Time': {'time': '..."
10,22,11,11,0,"{'driverId': 'tsunoda', 'permanentNumber': '22...","{'constructorId': 'alphatauri', 'url': 'http:/...",11,58,Finished,"{'millis': '5355285', 'time': '+1:29.371'}","{'rank': '7', 'lap': '40', 'Time': {'time': '1..."
11,24,12,12,0,"{'driverId': 'zhou', 'permanentNumber': '24', ...","{'constructorId': 'alfa', 'url': 'http://en.wi...",15,57,+1 Lap,NaN,"{'rank': '8', 'lap': '53', 'Time': {'time': '1..."
12,23,13,13,0,"{'driverId': 'albon', 'permanentNumber': '23',...","{'constructorId': 'williams', 'url': 'http://e...",19,57,+1 Lap,NaN,"{'rank': '13', 'lap': '40', 'Time': {'time': '..."
13,10,14,14,0,"{'driverId': 'gasly', 'permanentNumber': '10',...","{'constructorId': 'alphatauri', 'url': 'http:/...",17,57,+1 Lap,NaN,"{'rank': '19', 'lap': '16', 'Time': {'time': '..."
14,77,15,15,0,"{'driverId': 'bottas', 'permanentNumber': '77'...","{'constructorId': 'alfa', 'url': 'http://en.wi...",18,57,+1 Lap,NaN,"{'rank': '16', 'lap': '47', 'Time': {'time': '..."
15,47,16,16,0,"{'driverId': 'mick_schumacher', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",12,57,+1 Lap,NaN,"{'rank': '12', 'lap': '39', 'Time': {'time': '..."
16,20,17,17,0,"{'driverId': 'kevin_magnussen', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",16,57,+1 Lap,NaN,"{'rank': '20', 'lap': '40', 'Time': {'time': '..."
17,44,18,18,0,"{'driverId': 'hamilton', 'permanentNumber': '4...","{'constructorId': 'mercedes', 'url': 'http://e...",5,55,Hydraulics,NaN,"{'rank': '11', 'lap': '42', 'Time': {'time': '..."
18,6,19,19,0,"{'driverId': 'latifi', 'permanentNumber': '6',...","{'constructorId': 'williams', 'url': 'http://e...",20,55,Collision damage,NaN,"{'rank': '14', 'lap': '45', 'Time': {'time': '..."
19,14,20,R,0,"{'driverId': 'alonso', 'permanentNumber': '14'...","{'constructorId': 'alpine', 'url': 'http://en....",10,27,Water leak,NaN,"{'rank': '17', 'lap': '24', 'Time': {'time': '..."

In [13]:
df_results_2022['Driver'].apply(lambda x: x['driverId'])

0      max_verstappen
1             leclerc
2               perez
3               sainz
4             russell
           ...
15    mick_schumacher
16    kevin_magnussen
17           hamilton
18             latifi
19             alonso
Name: Driver, Length: 440, dtype: object

In [36]:
df_results_2022['points'] = df_results_2022['points'].astype(int)

In [37]:
df_results_2022.groupby(['Driver']).agg({'points':'sum'}).sort_values(by='points',ascending=False)

TypeError: unhashable type: 'dict'

In [38]:
df_results_2022.groupby(['Constructor']).agg({'points':'sum'}).sort_values(by='points', ascending=False)

TypeError: unhashable type: 'dict'

In [39]:
url = "http://ergast.com/api/f1/2008/5/results.json"
response = requests.get(url.format(race))
content = json.loads(response.content)

In [40]:
pd.DataFrame(content['MRData']['RaceTable']['Races'])

,season,round,url,raceName,Circuit,date,time,Results
0,2008,5,http://en.wikipedia.org/wiki/2008_Turkish_Gran...,Turkish Grand Prix,"{'circuitId': 'istanbul', 'url': 'http://en.wi...",2008-05-11,12:00:00Z,"[{'number': '2', 'position': '1', 'positionTex..."

In [44]:
content['MRData']['RaceTable']['Races'][0]['raceName']

'Bahrain Grand Prix'

## Tabla de resultados de url

In [92]:
url = "http://ergast.com/api/f1/seasons.json"
response = requests.get(url.format(2022))
content = json.loads(response.content)

In [93]:
content['MRData']

{'xmlns': 'http://ergast.com/mrd/1.5',
 'series': 'f1',
 'url': 'http://ergast.com/api/f1/seasons.json',
 'limit': '30',
 'offset': '0',
 'total': '74',
 'SeasonTable': {'Seasons': [{'season': '1950',
    'url': 'http://en.wikipedia.org/wiki/1950_Formula_One_season'},
   {'season': '1951',
    'url': 'http://en.wikipedia.org/wiki/1951_Formula_One_season'},
   {'season': '1952',
    'url': 'http://en.wikipedia.org/wiki/1952_Formula_One_season'},
   {'season': '1953',
    'url': 'http://en.wikipedia.org/wiki/1953_Formula_One_season'},
   {'season': '1954',
    'url': 'http://en.wikipedia.org/wiki/1954_Formula_One_season'},
   {'season': '1955',
    'url': 'http://en.wikipedia.org/wiki/1955_Formula_One_season'},
   {'season': '1956',
    'url': 'http://en.wikipedia.org/wiki/1956_Formula_One_season'},
   {'season': '1957',
    'url': 'http://en.wikipedia.org/wiki/1957_Formula_One_season'},
   {'season': '1958',
    'url': 'http://en.wikipedia.org/wiki/1958_Formula_One_season'},
   {'season': '1959',
    'url': 'http://en.wikipedia.org/wiki/1959_Formula_One_season'},
   {'season': '1960',
    'url': 'http://en.wikipedia.org/wiki/1960_Formula_One_season'},
   {'season': '1961',
    'url': 'http://en.wikipedia.org/wiki/1961_Formula_One_season'},
   {'season': '1962',
    'url': 'http://en.wikipedia.org/wiki/1962_Formula_One_season'},
   {'season': '1963',
    'url': 'http://en.wikipedia.org/wiki/1963_Formula_One_season'},
   {'season': '1964',
    'url': 'http://en.wikipedia.org/wiki/1964_Formula_One_season'},
   {'season': '1965',
    'url': 'http://en.wikipedia.org/wiki/1965_Formula_One_season'},
   {'season': '1966',
    'url': 'http://en.wikipedia.org/wiki/1966_Formula_One_season'},
   {'season': '1967',
    'url': 'http://en.wikipedia.org/wiki/1967_Formula_One_season'},
   {'season': '1968',
    'url': 'http://en.wikipedia.org/wiki/1968_Formula_One_season'},
   {'season': '1969',
    'url': 'http://en.wikipedia.org/wiki/1969_Formula_One_season'},
   {'season': '1970',
    'url': 'http://en.wikipedia.org/wiki/1970_Formula_One_season'},
   {'season': '1971',
    'url': 'http://en.wikipedia.org/wiki/1971_Formula_One_season'},
   {'season': '1972',
    'url': 'http://en.wikipedia.org/wiki/1972_Formula_One_season'},
   {'season': '1973',
    'url': 'http://en.wikipedia.org/wiki/1973_Formula_One_season'},
   {'season': '1974',
    'url': 'http://en.wikipedia.org/wiki/1974_Formula_One_season'},
   {'season': '1975',
    'url': 'http://en.wikipedia.org/wiki/1975_Formula_One_season'},
   {'season': '1976',
    'url': 'http://en.wikipedia.org/wiki/1976_Formula_One_season'},
   {'season': '1977',
    'url': 'http://en.wikipedia.org/wiki/1977_Formula_One_season'},
   {'season': '1978',
    'url': 'http://en.wikipedia.org/wiki/1978_Formula_One_season'},
   {'season': '1979',
    'url': 'http://en.wikipedia.org/wiki/1979_Formula_One_season'}]}}

In [97]:
seasons = {'season':[],
           'url':[]}

In [100]:
for item in content['MRData']['SeasonTable']['Seasons']:
    seasons['season'].append(int(item['season']))
    seasons['url'].append(item['url'])
    
pd.DataFrame(seasons)

    season                                                url
0     1950  http://en.wikipedia.org/wiki/1950_Formula_One_...
1     1951  http://en.wikipedia.org/wiki/1951_Formula_One_...
2     1952  http://en.wikipedia.org/wiki/1952_Formula_One_...
3     1953  http://en.wikipedia.org/wiki/1953_Formula_One_...
4     1954  http://en.wikipedia.org/wiki/1954_Formula_One_...
5     1955  http://en.wikipedia.org/wiki/1955_Formula_One_...
6     1956  http://en.wikipedia.org/wiki/1956_Formula_One_...
7     1957  http://en.wikipedia.org/wiki/1957_Formula_One_...
8     1958  http://en.wikipedia.org/wiki/1958_Formula_One_...
9     1959  http://en.wikipedia.org/wiki/1959_Formula_One_...
10    1960  http://en.wikipedia.org/wiki/1960_Formula_One_...
11    1961  http://en.wikipedia.org/wiki/1961_Formula_One_...
12    1962  http://en.wikipedia.org/wiki/1962_Formula_One_...
13    1963  http://en.wikipedia.org/wiki/1963_Formula_One_...
14    1964  http://en.wikipedia.org/wiki/1964_Formula_One_...
15    1965  http://en.wikipedia.org/wiki/1965_Formula_One_...
16    1966  http://en.wikipedia.org/wiki/1966_Formula_One_...
17    1967  http://en.wikipedia.org/wiki/1967_Formula_One_...
18    1968  http://en.wikipedia.org/wiki/1968_Formula_One_...
19    1969  http://en.wikipedia.org/wiki/1969_Formula_One_...
20    1970  http://en.wikipedia.org/wiki/1970_Formula_One_...
21    1971  http://en.wikipedia.org/wiki/1971_Formula_One_...
22    1972  http://en.wikipedia.org/wiki/1972_Formula_One_...
23    1973  http://en.wikipedia.org/wiki/1973_Formula_One_...
24    1974  http://en.wikipedia.org/wiki/1974_Formula_One_...
25    1975  http://en.wikipedia.org/wiki/1975_Formula_One_...
26    1976  http://en.wikipedia.org/wiki/1976_Formula_One_...
27    1977  http://en.wikipedia.org/wiki/1977_Formula_One_...
28    1978  http://en.wikipedia.org/wiki/1978_Formula_One_...
29    1979  http://en.wikipedia.org/wiki/1979_Formula_One_...

In [104]:
pd.DataFrame(seasons).to_csv('seasons.csv', index = False)